name: CI

on: [push]

jobs:
  unittest-NumericalAnalysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build clear
      run: rm -r ./build
    - name: build
      run: |
        cmake -S . -B build
        cmake --build build --config RELEASE
    - name: run
      run: ./build/test/NumericalAnalysis/Release/test.exe
