name: CI

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: delete build directory
      run: |
        ls
        rm -r ./build
    - name: run release build
      run: |
        cmake -S . -B build
        cmake --build build --config Release
    - name: run googletest
      run: |
        cd ${{ github.workspace }}
        ./build/test/test_all
    - name: delete CMakeCache
      run: |
        ls
        rm ./build/CMakeCache.txt
        