name: CI

on: [push]

jobs:
  unittest-NumericalAnalysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        rm ./build/CMakeCache.txt
        cmake -S . -B build
        cmake --build build
    - name: run
      run: ./build/test/NumericalAnalysis/Debug/test
